apiVersion: v1
kind: Pod
metadata:
  name: nginx123
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

  - name: ubuntu
    image: ubuntu
    command: ['sleep', '1000']
