version: "3.8"  # Define the Compose file version

services:
  web:
    image: myapp_web:latest
    ports:
      - "8080:80"  # Host:Container (port binding)
    volumes:
      - ./web:/usr/share/nginx/html:ro  # Local dir to container (read-only)
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - frontend
      - backend
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: examplepass
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db_data:  # Named volume for persistent DB storage

networks:
  frontend:  # Custom network for front-facing services
  backend:   # Custom network for internal services
