services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      - FLASK_ENV=development

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: votesdb
    ports:
      - "5432:5432"

